Schedule  page
sdtorresl/icfesapp pull request #7
Opened 2020-10-09 23:34 UTC by Duvan0902

2020-10-13 13:23 UTC, sdtorresl requested changes
@Duvan0902 , por fa revisa cada comentario y resuelvelos lo más pronto posible para aprobar este PR

2020-10-13 13:23 UTC, sdtorresl commented on android/app/src/main/res/values/styles.xml
> +        <style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar">
¿Para qué agregaste este espacio extra? quedó mal indentado

2020-10-13 13:23 UTC, sdtorresl commented on android/settings_aar.gradle
> +include ':app'
Y esto? ¿lo generaste tu o fue automático?

2020-10-13 13:23 UTC, sdtorresl commented on lib/common/document_download.dart
> +                    .copyWith(color: Colors.black)),
No olvides dejar las comas para indentar bien

2020-10-13 13:23 UTC, sdtorresl commented on lib/common/document_download.dart
>          onLongPress: () {},
Este método debe permitir que el usuario descargue los documentos adjuntos de acuerdo al webservice proporcionado. Por favor completar esta funcionalidad.

2020-10-13 13:23 UTC, sdtorresl commented on lib/common/onboarding1.dart
> +class Onboarding1 extends StatelessWidget {
Hay tres widgets que están haciendo lo mismo, tienen código repetido. Esta no es la forma más apropiada para propgramar esta parte, se puede optimizar mucho más.

2020-10-13 13:23 UTC, sdtorresl commented on lib/common/poster_desing.dart
> +  const DesingPoster({
Nuevamente, no es desing, es "design"

2020-10-13 13:23 UTC, sdtorresl commented on lib/common/poster_desing.dart
> +  const DesingPoster({
Aunque igual, "diseño de poster" no creo que sea el nomre más apropiado.

2020-10-13 13:23 UTC, sdtorresl commented on lib/common/rooms_dropdown.dart
> +              child: _roomsCategoriesDropDown(),
¿Por qué categorías?
Que yo recuerde, la salas no tienen categorías

2020-10-13 13:23 UTC, sdtorresl commented on lib/pages/onboarding_page.dart
> +              items: [
Acá es la parte clave, por qué llamar tres widgets diferentes que hacen lo mismo?
¿no es mejor usar un solo widget con parámetros diferentes?

2020-10-13 14:18 UTC, Duvan0902 commented on android/settings_aar.gradle
> +include ':app'
Buenos días ingeniero no señor uo no lo genere

2020-10-15 15:29 UTC, Duvan0902 commented on android/app/src/main/res/values/styles.xml
> +        <style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar">
Buenos días ingeniero el espacio ya fue corregido en esta sección.

2020-10-15 15:30 UTC, Duvan0902 commented on lib/common/document_download.dart
> +                    .copyWith(color: Colors.black)),
La comas ya fueron puestas en sus respectivos corchetes, con el fin de que el codigo quede bien indentado.

2020-10-15 15:31 UTC, Duvan0902 commented on lib/common/document_download.dart
>          onLongPress: () {},
La funcionalidad ya fue aplicada, el usuario ya puedo observar los documentos.

2020-10-15 15:35 UTC, Duvan0902 commented on lib/common/onboarding1.dart
> +class Onboarding1 extends StatelessWidget {
se optimizo mucho el codigo respecto a onbording, adicionalmente se realizaron unos cambios adicionales para la transición de este mismo.

2020-10-15 15:35 UTC, Duvan0902 commented on lib/common/poster_desing.dart
> +  const DesingPoster({
Efectivamente el nombre no fue el apropiado por ende se realizo su respectivo cambio.

2020-10-15 15:35 UTC, Duvan0902 commented on lib/common/rooms_dropdown.dart
> +              child: _roomsCategoriesDropDown(),
fue un error de nombre, aun así, este ya fue modificado.

2020-10-15 15:35 UTC, Duvan0902 commented on lib/pages/onboarding_page.dart
> +              items: [
Al optimizar onboarding, se hizo el uso debido para usar un solo widget.

2020-10-15 15:45 UTC, sdtorresl requested changes

2020-10-15 15:45 UTC, sdtorresl commented on lib/common/onboarding2.dart
> +class Onboarding2 extends StatelessWidget {
¿Por qué esto todavía está?

2020-10-15 15:45 UTC, sdtorresl commented on lib/common/onboarding3.dart
> +class Onboarding3 extends StatelessWidget {
Y esto?

2020-10-15 15:45 UTC, sdtorresl commented on lib/common/rooms_dropdown.dart
> +          List<ScheduleModel> categories = snapshot.data;
Sigo sin entender que son categorias en la agenda

2020-10-15 15:45 UTC, sdtorresl commented on lib/common/rooms_dropdown.dart
> +  String searchText;
Y esto para qué es?

2020-10-15 16:00 UTC, Duvan0902 commented on lib/common/onboarding3.dart
> +class Onboarding3 extends StatelessWidget {
Onboarding3 ya fue eliminado

2020-10-15 16:33 UTC, sdtorresl approved these changes

2020-10-15 16:33 UTC, merged