Rooms
sdtorresl/icfesapp pull request #8
Opened 2020-10-17 22:58 UTC by Duvan0902

2020-10-17 23:09 UTC, sdtorresl requested changes

2020-10-17 23:09 UTC, sdtorresl commented on lib/common/material_list.dart
> +class MaterialList extends StatelessWidget {
Es mejor renombrar esta clase para evitar conflictos con la libreria "Material" de Android.

RedordedList está bien

2020-10-17 23:09 UTC, sdtorresl commented on lib/common/room_list.dart
> +
Para qué este espacio adicional?

2020-10-17 23:09 UTC, sdtorresl commented on lib/pages/prerecorded _material_page.dart
> +class SchedulePage extends StatelessWidget {
Esta clase no debería llamarse diferente?

2020-10-17 23:09 UTC, sdtorresl commented on lib/pages/prerecorded _material_page.dart
> +import 'package:icfesapp/common/schedule_list..dart';
¿Para qué importar esa libreria?

2020-10-17 23:09 UTC, sdtorresl commented on lib/pages/rooms_page.dart
> +  Widget materiaLists(context) {
Este widget está mal escrito. Además, debe evitarse conflictos con la clase Material de google.

2020-10-17 23:09 UTC, sdtorresl commented on lib/providers/prerecorded_provider.dart
> +        List<PrerecordedModel> materials = List();
Renombrar esta variable

2020-10-17 23:09 UTC, sdtorresl commented on lib/providers/prerecorded_provider.dart
> +      print("Aqui");
Quita esto

2020-10-18 02:11 UTC, Duvan0902 commented on lib/common/material_list.dart
> +class MaterialList extends StatelessWidget {
Ya se realizaron los cambios correspondientes.

2020-10-18 02:11 UTC, Duvan0902 commented on lib/common/room_list.dart
> +
Se redujo el espacio adicional,

2020-10-18 02:20 UTC, Duvan0902 commented on lib/pages/prerecorded _material_page.dart
> +class SchedulePage extends StatelessWidget {
La clase fue nombrada de esa manera, debido a que, el ingeniero me pidio colocarle es nombre.

2020-10-18 02:53 UTC, Duvan0902 commented on lib/pages/rooms_page.dart
> +  Widget materiaLists(context) {
la variable ya fue cambiada.

2020-10-18 02:54 UTC, Duvan0902 commented on lib/providers/prerecorded_provider.dart
> +        List<PrerecordedModel> materials = List();
se realizo el debido renombramiento de esta variable.

2020-10-18 22:17 UTC, sdtorresl approved these changes

2020-10-18 22:17 UTC, merged